version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    depends_on:
      - "db"
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    # image: staticfloat/nginx-certbot
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTBOT_EMAIL: excursionsapp@gmail.com
    volumes:
      - ./:/var/www
      # - ./nginx/conf.d/:/etc/nginx/user.conf.d:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      # - letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports: 
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  # letsencrypt:
  #   driver: local
